esp_toml_version = 1.0
firmware_images_url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_meter_pro_v2@9c439e956d59f5b4dbcef8e645a5fb7a5490fa42/firmware/v0.5.0/"
supported_apps = ["Wireless_power_meter_pro_v2"]

["Wireless_power_meter_pro_v2"]
image.esp32c6 = "Wireless_power_meter_pro_v2_merged_v0.5.0.bin"
description = "Pro V2 版本功率计固件-手动烧录"
android_app_url = ""
ios_app_url = ""
chipsets = ["esp32c6"]
