esp_toml_version = 1.0
version = "0.6.0"
published_at = "2026-10-02T05:02:09Z"

[firmware]
app = "Wireless_power_meter_pro_v2_app_v0.6.0.bin"
app_size = 1324816
app_url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_meter_pro_v2@88665b62122bd62e0b4e7e827a78a6dcf063c1c0/firmware/v0.6.0/Wireless_power_meter_pro_v2_app_v0.6.0.bin"
merged = "Wireless_power_meter_pro_v2_merged_v0.6.0.bin"
merged_size = 1455888
merged_url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_meter_pro_v2@88665b62122bd62e0b4e7e827a78a6dcf063c1c0/firmware/v0.6.0/Wireless_power_meter_pro_v2_merged_v0.6.0.bin"
